name: spot_mobile
description: Application mobile Spot. pour la réservation de services
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Network
  dio: ^5.4.0
  
  # Storage sécurisé (JWT)
  flutter_secure_storage: ^9.0.0
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Date formatting
  intl: ^0.20.2
  
  # JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
